blank_issues_enabled: false
contact_links:
  - name: Lightning Talks: Questions/Ideas/Feedback
    url: https://github.com/orgs/Virtual-Coffee/teams/lightning-talk-team/discussions
    about: Please ask and answer questions here.
